import { YouTubeTranscriptApi } from "@hallelx/youtube-transcript";

type Body = {
  url?: string;
  videoId?: string;
  language?: string;
  includeSegments?: boolean;
  format?: "json" | "text" | "srt";
  sourcePreference?: "any" | "manual" | "generated";
  translateTo?: string;
};

function extractVideoId(input: string): string | null {
  const raw = input.trim();
  if (/^[A-Za-z0-9_-]{11}$/.test(raw)) return raw;
  try {
    const u = new URL(raw);
    if (u.hostname === "youtu.be") {
      const id = u.pathname.replace("/", "").split("/")[0];
      return /^[A-Za-z0-9_-]{11}$/.test(id) ? id : null;
    }
    if (u.hostname.includes("youtube.com")) {
      if (u.pathname === "/watch") {
        const id = u.searchParams.get("v");
        return id && /^[A-Za-z0-9_-]{11}$/.test(id) ? id : null;
      }
      const m = u.pathname.match(/^\/(?:shorts|embed|live)\/([A-Za-z0-9_-]{11})/);
      return m ? m[1] : null;
    }
  } catch {}
  return null;
}

function srtTime(ms: number): string {
  const h = Math.floor(ms / 3600000);
  const m = Math.floor((ms % 3600000) / 60000);
  const s = Math.floor((ms % 60000) / 1000);
  const milli = ms % 1000;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")},${String(milli).padStart(3, "0")}`;
}

export default async function handler(req: Request) {
  if (req.method !== "POST") return Response.json({ error: "POST required" }, { status: 405 });
  let body: Body;
  try { body = await req.json(); } catch { return Response.json({ error: "Invalid JSON body" }, { status: 400 }); }

  const videoId = extractVideoId(body.videoId ?? body.url ?? "");
  if (!videoId) return Response.json({ error: "Provide a valid YouTube URL or 11-character videoId" }, { status: 400 });
  const format = body.format ?? "json";
  if (!["json", "text", "srt"].includes(format)) return Response.json({ error: "format must be json, text, or srt" }, { status: 400 });
  const sourcePreference = body.sourcePreference ?? "any";
  if (!["any", "manual", "generated"].includes(sourcePreference)) return Response.json({ error: "sourcePreference must be any, manual, or generated" }, { status: 400 });

  try {
    const api = new YouTubeTranscriptApi();
    let fetched: any;
    if (sourcePreference === "any" && !body.translateTo) {
      const options = body.language ? { languages: [body.language] } : undefined;
      fetched = await api.fetch(videoId, options as any);
    } else {
      const list: any = await api.list(videoId);
      const all: any[] = Array.from(list as any);
      const languageCodes = body.language ? [body.language] : all.filter((t: any) => sourcePreference === "any" || (sourcePreference === "generated" ? t.isGenerated : !t.isGenerated)).map((t: any) => t.languageCode);
      if (!languageCodes.length) throw new Error(`No ${sourcePreference} transcript track available`);
      let selected: any;
      if (sourcePreference === "manual") selected = list.findManuallyCreatedTranscript(languageCodes);
      else if (sourcePreference === "generated") selected = list.findGeneratedTranscript(languageCodes);
      else selected = list.findTranscript(languageCodes);
      if (body.translateTo) {
        if (!selected.isTranslatable) throw new Error(`Selected transcript cannot be translated to ${body.translateTo}`);
        selected = selected.translate(body.translateTo);
      }
      fetched = await selected.fetch();
    }

    const raw = typeof fetched?.toRawData === "function" ? fetched.toRawData() : [];
    const segments = raw.map((s: any) => ({ text: String(s.text ?? "").replace(/\s+/g, " ").trim(), offsetMs: Math.round(Number(s.start ?? 0) * 1000), durationMs: Math.round(Number(s.duration ?? 0) * 1000) })).filter((s: any) => s.text);
    const transcript = segments.map((s: any) => s.text).join(" ").replace(/\s+/g, " ").trim();
    if (!transcript) return Response.json({ success: false, videoId, error: "Transcript returned no text" }, { status: 422 });
    const srt = segments.map((s: any, i: number) => `${i + 1}\n${srtTime(s.offsetMs)} --> ${srtTime(s.offsetMs + Math.max(s.durationMs, 1))}\n${s.text}`).join("\n\n");
    const payload: any = { success: true, videoId, videoUrl: `https://www.youtube.com/watch?v=${videoId}`, language: fetched?.languageCode ?? body.translateTo ?? body.language ?? null, languageName: fetched?.language ?? null, autoGenerated: Boolean(fetched?.isGenerated), sourcePreference, translated: Boolean(body.translateTo), translateTo: body.translateTo ?? null, format, transcript, formatted: format === "srt" ? srt : transcript, wordCount: transcript.split(/\s+/).filter(Boolean).length, characterCount: transcript.length, fetchedAt: new Date().toISOString() };
    if (body.includeSegments || format === "srt") payload.segments = segments;
    return Response.json(payload);
  } catch (error: any) {
    return Response.json({ success: false, videoId, error: "Transcript unavailable", detail: String(error?.message ?? error) }, { status: 422 });
  }
}
